packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@marsidev/react-turnstile': 1.4.1
  '@next/bundle-analyzer': 16.1.1
  '@next/eslint-plugin-next': 16.1.1
  '@stripe/react-stripe-js': 5.4.1
  '@stripe/stripe-js': 8.6.1
  '@supabase/supabase-js': 2.89.0
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.16
  '@types/node': 25.0.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  eslint-config-next: 16.1.1
  lucide-react: 0.562.0
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  react-hook-form: 7.70.0
  react-i18next: 16.5.1
  stripe: 20.1.1
  supabase: 2.71.2
  tailwindcss: 4.1.18
  tw-animate-css: 1.4.0
  zod: 3.25.76

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
